name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/aplikasi-management-karyawan
          git pull origin master
          pip install -r requerements.txt
          mysql -u root -p${{ secrets.DB_PASSWORD }} -e "drop database kepegawaian"
          mysql -u root -p${{ secrets.DB_PASSWORD }} -e "create database kepegawaian"
          mysql -u root -p${{ secrets.DB_PASSWORD }} kepegawaian < database/kepegawaian.sql
          sudo systemctl restart aplikasi-management-karyawan.service